### ISSUE TITLE
stomp input plugin in logstash 2.0.0 creates an error

### ISSUE THREAD

**Issue by Amrgt** [logstash-plugins/logstash-input-stomp#10]
The config seems ok but when launching logstash, the following error pops up: 

A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::Stomp host=>"localhost", user=>"admin", password=><password>, destination=>"queue", debug=>false, codec=><LogStash::Codecs::Plain charset=>"UTF-8">, port=>61613>
  Error: undefined method `subscribe' for nil:NilClass {:level=>:error}

My configuration is the following:
input {
    stomp {
        host => "localhost"
    user => "admin"
    password => "password"
    destination => "queue"
    }
}

**Comment by francesco-coletta** [comment]
+1

My configuration is:

input {
    stomp {
        host => "localhost"
        port => 61613
        destination => "rheticus.processor.ps.log"
        debug => true
    }  
}

**Comment by wiibaa** [comment]
Hello, sorry that you are having a hard time with this plugin, can you please both of you provide some extra info
- What is your stomp server (rabbitmq , activemq ...)
- can you run  logstash with the **--debug** flag and spot any occurence of **Failed to connect to stomp server** and post the details here. You should see something similar to 

```
Failed to connect to stomp server, will retry {:exception=>#<NoMethodError: undefined method `connect' for nil:NilClass>, :backtrace=>[...
```

Thanks

**Comment by wiibaa** [comment]
@andrewvc I do not want to point an accusing finger, just need your confirmation here. It seems that your last commit is involved/responsible for breaking this plugin https://github.com/logstash-plugins/logstash-input-stomp/commit/897454ec81655c7bafb991262f41d0bcc1c5ab64
Even when setting attr_accessor for the purpose of mocking in the test, changing client from an ivar to a local var was a no-go, right ?

**Comment by andrewvc** [comment]
@wiibaa apologies, some stuff got messed up in the mass updating I was doing. 

We're trying to tackle the root of this problem by upping our test coverage, but this plugin hasn't gotten the love yet :( .

I'm on the road the next couple weeks, but maybe one of you guys can submit a PR to fix this?

**Comment by andrewvc** [comment]
Perhaps @suyograo there's someone who can focus on fixing this + improving the specs while I'm out?

Once again, apologies to all here for the breakage :(

**Comment by dybakore** [comment]
> Is this issue resolved? I am still getting the following error with Logstash 2.1 and Active MQ

`Flushing buffer at interval {:instance=>"#<LogStash::Outputs::ElasticSearch::Buffer:0x4481a83d @stopping=#<Concurrent::AtomicBoolean:0x1c4c5fee>, @last_flush=2016-01-19 23:01:26 UTC, @flush_thread=#<Thread:0x2f3d7738 run>, @max_size=500, @operations_lock=#<Java::JavaUtilConcurrentLocks::ReentrantLock:0x6c5e15c2>, @submit_proc=#<Proc:0x33ed918d@/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.2.0-java/lib/logstash/outputs/elasticsearch/common.rb:55>, @flush_interval=1, @logger=#<Cabin::Channel:0x31eeda9d @subscriber_lock=#<Mutex:0x38529307>, @data={}, @metrics=#<Cabin::Metrics:0x3532cd74 @channel=#<Cabin::Channel:0x31eeda9d ...>, @metrics={}, @metrics_lock=#<Mutex:0x1a4e95f5>>, @subscribers={12672=>#<Cabin::Outputs::IO:0x3f616905 @lock=#<Mutex:0x1435e7c5>, @io=#<IO:fd 1>>}, @level=:debug>, @buffer=[], @operations_mutex=#<Mutex:0x5f0340e0>>", :interval=>1, :level=>:info, :file=>"logstash/outputs/elasticsearch/buffer.rb", :line=>"90", :method=>"interval_flush"}
A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::Stomp host=>"127.0.0.1", destination=>"/topics/bgx_connect_topic", debug=>true, port=>61613, codec=><LogStash::Codecs::JSON charset=>"UTF-8">, password=><password>>
  Error: undefined method`subscribe' for nil:NilClass
  Exception: NoMethodError
  Stack: /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-stomp-2.0.2/lib/logstash/inputs/stomp.rb:71:in `subscription_handler'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-stomp-2.0.2/lib/logstash/inputs/stomp.rb:91:in`run'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/pipeline.rb:206:in `inputworker'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/pipeline.rb:199:in`start_input' {:level=>:error, :file=>"logstash/pipeline.rb", :line=>"218", :method=>"inputworker"}`

Here is my config:

> input {
>   stomp {
>       host => "127.0.0.1"
>       destination => "/topics/mytopic"
>       debug => true
>       port => "61613"
>         codec => "json"
>     }

**Comment by wiibaa** [comment]
@dhananjaybakore The issue is indeed still present with version 2.0.2

@purbon do you have time to push 2.0.3 to rubygems

**Comment by suyograo** [comment]
@wiibaa published 2.0.3 now

**Comment by suyograo** [comment]
@dhananjaybakore you can do `bin/plugin install --version 2.0.3 logstash-input-stomp` to get the latest version

**Comment by wiibaa** [comment]
Thanks @suyograo :+1:
